# Generated by Django 4.2.7 on 2024-11-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
