# Generated by Django 4.2.7 on 2024-11-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_orders_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordertime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
