# Generated by Django 4.2.7 on 2024-11-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_orders_orderdate_alter_orders_ordertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='orderdate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ordertime',
        ),
        migrations.AddField(
            model_name='orders',
            name='orderdatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
