# Generated by Django 4.2.7 on 2024-11-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_orders_orderdate_remove_orders_ordertime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='CustomUser.phone', max_length=12, verbose_name='Телефон'),
        ),
    ]
